### ISSUE TITLE
slow computation network construction

### ISSUE THREAD

**Issue by sander2** [szabta89/IncA#16]
Building the computation network takes a long time for complicated analyses (this should be reported to Viatra at some point); in my case, it takes about 10-15s. This initialization seems to be separately for each model that is analyzed. As a result, my test suite, which analyzed three different models, spent a lot of time recomputing the  computation network. For now, I have merged all my three (test program) models to greatly speedup testing time.

**Comment by szabta89** [comment]
This is an obsolete issue, closing it.
