### ISSUE TITLE
Universal quantification

### ISSUE THREAD

**Issue by sander2** [szabta89/IncA#18]
It happens quite often that you need to assert that a function is defined for all items in some list (or set of tuples). There are ways to implement this in IncA, but they each have their drawbacks. 

1. Through recursion

```
def containerOk(c: Container) {
  e := c.elems
  assert undef e.prev
  assert def checkElemListRecursively(e)
} alt {
  assert undef c.elems
}
def checkElemListRecursively(e: Elem) {
  // omitted: assert that e is valid

  switch {
    assert undef e.next
  } alt {
    assert def checkElemListRecursively(e.next)
  }
}
```

This is not very nice to write and the recursive nature likely has a negative impact on the performance. Also, it only works on lists and not on a set a values returned by a function.

2. Through negation

```
def containerOk(c: Container) {
  assert undef containerElemNok(c)
}
def containerElemNok(c: Container) {
  e := c.elems
  // omitted: assert that e is invalid
}
```

This has the downside that it uses `undef`, which in some situations can lead to negation in recursion. On the upside, there is less boilerplate required than the other solutions.

3. Through lattice aggregation

```
def containerOk(c: Container) {
  assert containerElemOk(c) == BoolLattice.True
}
def containerElemOk(c: Container) : BoolLattice/intersection {
  e := c.elems
  
  switch {
    assert def elemOk(e)
    return BoolLattice.True 
  } alt {
    assert undef elemOk(e)
    return BoolLattice.False
  }
} alt {
  assert undef c.elems
  return BoolLatice.True
}
def elemOk(e: Elem) {
    // omitted: assert that e is valid
}
```

Like the previous solution, this has the downside that an `undef` is required (in the second alternative of the switch). Also, it's a bit verbose. However, its performance is likely better than the recursive solution.

## Ideal solution

Some kind of support for universal quantification. Something like the example below would be ideal.
```
def containerOk(c: Container) {
  // universal quantification on a list:
  foreach e in c.elems {
    // omitted: assert that e is valid
  }
  // it would be even better if it would also work on the result of a function call:
  foreach e in getAllElems(c) {
    // omitted: assert that e is valid
  }
}
```

## Implementation

It's probably fairly easy to transform the suggested syntax into code as shown in case 2 or 3. That would, however, introduce `assert undef`s. Could these be avoided somehow?

**Comment by sander2** [comment]
@seba-- we talked about how something like option 3 would be implementable without using an undef. You mentioned that using an invertible operation could help; i.e. by making `elemOk` return either 0 or 1 and to compare the sum of these to the size of the list. While I see how using the invertible operation would be more efficient than maintaining a tree, it doesn't solve the undef issue, does it? Wouldn't `elemOk` still need to use an undef internally to determine whether `0` should be returned..?

**Comment by seba--** [comment]
If you return `1` when `elemOk(e)` holds and nothing otherwise, this is enough. Then the `sum` aggregation counts the number of elements satisfying `elemOk`.

-- 
http://erdweg.org

**Comment by szabta89** [comment]
This is an obsolete issue, closing it.
