### ISSUE TITLE
unexpected behavior in `assert undef a.b.c`

### ISSUE THREAD

**Issue by sander2** [szabta89/IncA#3]
These two snippets behave differently when `a.b` is defined, but `a.b.c` is not:

```
assert undef a.b.c
```
and
```
tmp := a.b
assert undef tmp.c
```

Ideally, `assert undef a.b.c` should be equivalent to:
```
switch{
    assert undef a.b
} alt {
    tmp := a.b
    assert undef tmp.c
}
```
If that's not possible, then only using the second part of the switch would be acceptable. If that's not possible either, then a compiler error should be thrown when this construct is used.

**Comment by szabta89** [comment]
@sander2 Can you provide me a concrete example where the results of the two snippets differ?

**Comment by sander2** [comment]
Pushed to [issue3](https://github.com/sander2/mps-rust/tree/issue3).

**Comment by szabta89** [comment]
Ok, I see your point now. 

Here is what I think we should do:
* Extend the checking rule for the undef in a way that it only allows two kinds of things: (1) undef on a function call and (2) undef on a path expression that starts with a reference to a variable.
* Implement a small rewriting in the generator that takes care of (2) by rewriting it into a series of pattern function alternative bodies following your idea.
