### ISSUE TITLE
Binding generated data

### ISSUE THREAD

**Issue by sander2** [szabta89/IncA#5]
Using strings that are generated by Java code are handled incorrectly. This works:

```
assert MyLattice.randomString() == "test"
```

But this does not:
```
x := MyLattice.randomString()
assert x == "test"
```

You explained that generated data can never be returned from a pattern function, but that it should be allowed to be bound to temporary variables. However, during compilation, the code is transformed in such a way that all variables are returned as part of a generated function. Thus, the transformed code is illegal and does not work.

**Comment by szabta89** [comment]
This is an obsolete issue, closing it.
